#!/usr/bin/env bash
# Killing the process named 7-highlander

pid=$(pgrep -f "7-highlander")


if [ -n "$pid" ]; then
    # Kill the process
    kill "$pid"
    echo "Process 7-highlander (PID: $pid) killed."
else
    echo "Process 7-highlander not found."
fi
